version: 4.2.{build}-alpha
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: 'src/ENet.Managed/ENet.Managed.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    dotnet restore

    dotnet build ENet.Managed.sln -c Release -o build-output

    dotnet pack src\ENet.Managed\ENet.Managed.csproj -c Release -o nuget-packs
test_script:
- cmd: dotnet test ENet.Managed.sln -c Debug
artifacts:
- path: build-output
  name: ENet.Managed-build
- path: nuget-packs\*.nupkg
  name: ENet.Managed-nugets