version: 5.0.{build}-alpha
image: Visual Studio 2019
build_script:
- cmd: >-
    dotnet restore

    dotnet build ENet.Managed.sln -c Release -o build-output

    dotnet pack src\ENet.Managed\ENet.Managed.csproj -c Release -o nuget-packs -p:PackageVersion=%APPVEYOR_BUILD_VERSION% -p:AssemblyVersion=%APPVEYOR_BUILD_VERSION%
test_script:
- cmd: dotnet test ENet.Managed.sln -c Debug
artifacts:
- path: build-output
  name: ENet.Managed-build
- path: nuget-packs\*.nupkg
  name: ENet.Managed-nugets